//--------------//
// ASYNCHRONOUS //
//--------------//

// SUCCESS
export const TAGS_SUCCESS = 'TAGS_SUCCESS';
export const ALL_TAGS_SUCCESS = 'ALL_TAGS_SUCCESS';
export const RELATIONS_SUCCESS = 'RELATIONS_SUCCESS';
export const PHOTOS_SUCCESS = 'PHOTOS_SUCCESS';
export const ALL_PHOTOS_SUCCESS = 'ALL_PHOTOS_SUCCESS';

export const NEW_PHOTO_SUCCESS = 'NEW_PHOTO_SUCCESS';
export const NEW_TAG_SUCCESS = 'NEW_TAG_SUCCESS';
export const NEW_RELATION_SUCCESS = 'NEW_RELATION_SUCCESS';

export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const VIEWING_USER_SUCCESS = 'VIEWING_USER_SUCCESS';

export const RUD_RELATION_LOADING = 'RUD_RELATION_LOADING';
export const RUD_RELATION_SUCCESS = 'RUD_RELATION_SUCCESS';
export const RUD_RELATION_FAILURE = 'RUD_RELATION_FAILURE';

export const LOGOUT = 'LOGOUT';

export const RUD_TAG_LOADING = 'RUD_TAG_LOADING';
export const RUD_TAG_SUCCESS = 'RUD_TAG_SUCCESS';
export const RUD_TAG_FAILURE = 'RUD_TAG_FAILURE';

export const RUD_PHOTO_LOADING = 'RUD_PHOTO_LOADING';
export const RUD_PHOTO_SUCCESS = 'RUD_PHOTO_SUCCESS';
export const RUD_PHOTO_FAILURE = 'RUD_PHOTO_FAILURE';

export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_LOADING = 'USER_INFO_LOADING';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';
export const FAVORITES_SUCCESS = 'FAVORITES_SUCCESS';
export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILURE = 'FAVORITES_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// LOADING
export const TAGS_LOADING = 'TAGS_LOADING';
export const ALL_TAGS_LOADING = 'ALL_TAGS_LOADING';
export const RELATIONS_LOADING = 'RELATIONS_LOADING';
export const PHOTOS_LOADING = 'PHOTOS_LOADING';
export const ALL_PHOTOS_LOADING = 'ALL_PHOTOS_LOADING';

export const NEW_PHOTO_LOADING = 'NEW_PHOTO_LOADING';
export const NEW_TAG_LOADING = 'NEW_TAG_LOADING';
export const NEW_RELATION_LOADING = 'NEW_RELATION_LOADING';

export const AUTHENTICATION_LOADING = 'AUTHENTICATION_LOADING';
export const ALL_USERS_LOADING = 'ALL_USERS_LOADING';

// FAILURE
export const TAGS_FAILURE = 'ALL_TAGS_FAILURE';
export const ALL_TAGS_FAILURE = 'ALL_TAGS_FAILURE';
export const RELATIONS_FAILURE = 'RELATIONS_FAILURE';
export const PHOTOS_FAILURE = 'PHOTOS_FAILURE';
export const ALL_PHOTOS_FAILURE = 'ALL_PHOTOS_FAILURE';

export const NEW_PHOTO_FAILURE = 'NEW_PHOTO_FAILURE';
export const NEW_TAG_FAILURE = 'NEW_TAG_FAILURE';
export const NEW_RELATION_FAILURE = 'NEW_RELATION_FAILURE';

export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const ALL_USERS_FAILURE = 'ALL_USERS_FAILURE';
export const VIEWING_USER_FAILURE = 'VIEWING_USER_FAILURE';
//-------------//
// SYNCHRONOUS //
//-------------//
export const SET_TAGS = 'SET_TAGS';
